name: Release APK

env:
  main_project_module: app
  app_name: Find my IP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Run gradle tests
        run: ./gradlew --no-daemon test

      - name: Build gradle project
        run: ./gradlew --no-daemon buildRelease

      - name: Build apk release
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.app_name }} release
          path: app/build/outputs/apk/release
          if-no-files-found: error

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Upload signed APK Release
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.app_name }} release signed
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          if-no-files-found: error
